apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  namespace: web-app
spec:
  selector:
    app: streamlit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: NodePort
